### ISSUE TITLE
Upgrade to WebSocket required

### ISSUE THREAD

**Issue by SchweinchenFuntik** [JPro-one/JPro-tickets#105]
Through index.html, the application normally opens, if you manually write the path to it, then it swears at sockets.

`http://localhost:8088/app/name` - result `Upgrade to WebSocket required`
`http://localhost:8088` - work

**index.html**
```html
<!DOCTYPE html>

<html>
    <head>
        <title>Name</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="/jpro/css/jpro-fullscreen.css">
        <link rel="stylesheet" type="text/css" href="/jpro/css/jpro.css">
        <script src="/jpro/js/jpro.js" type="text/javascript"></script>

    </head>

    <body>
        <jpro-app href="/app/recorder" fullscreen="true" scale="false" stretch="false" disableShadows="true" disableEffects="true" readonly="false"></jpro-app>
    </body>
</html>
```

Browser using proxy. 
If you need more information, I can provide

**Comment by FlorianKirmaier** [comment]
The url http://localhost:8088/app/name  is only used internally.
So the user/browser shouldn't open it.

Some proxies might not support websocket, which is a standard nowadays.
We usually recommend using SSL to prevent proxies from manipulating the traffic - which is especially a problem in corporate intranets. You can test whether this would fix the problem, by checking whether jpro.one works with the proxy.

**Comment by SchweinchenFuntik** [comment]
Everything works, only full URL requests don't work. The application works for me only for the local network.

**Comment by FlorianKirmaier** [comment]
As mentioned , websocket is currently required. Some proxies don't support this. SSL helps with proxies.
