### ISSUE TITLE
FileNotFoundException using linux and 2018.1.8

### ISSUE THREAD

**Issue by ryppo** [JPro-one/JPro-tickets#11]
Unfortunately update 2018.1.8 brings a bug. 
Configuration: Linux, JPro 2018.1.8
Use case: Upload a file to the application. This works fine. Later call 
`String fileContent = FileUtils.readFileToString(sourceFile, Charset.defaultCharset());`
creates
`java.io.FileNotFoundException: File './tmp/-4188487734748623408/<my-filename>' does not exist`
Investion shows that the named folder is created, but it is empty.

Current two solutions:

- Use Windows
- Use JPro 2018.1.7

**Comment by FlorianKirmaier** [comment]
@ryppo 
On a quick test, I haven't been able to replicate the problem on Mac.

I have some questions about the issue:
* Are you using `WebAPI.FileUploader` to upload the file?
* Does it only happen on Linux?
* What is the default encoding for the JVM? (You can see it in the `/status` page)
* Did you test it for JPro 2018.1.7 + Linux? Did it work?
* Does it happen on any file, or only with files containg whitespaces, specialcharacters etc.?

**Comment by ryppo** [comment]
Thank you for quick answer.

- I did not test on Mac, because it is not use case for the current project. On Win 10 it works, on Linux not.
- FileUpload feature is created in this way: `WebAPI.getWebAPI(myScene).makeFileUploadNode(myTableView);` to prepare file-dropping
- encoding is `UTF-8`
- java version is `1.8.0_191`
- Switching back to JPro 2018.1.7 is my current configuration, because this works fine
- Typical filename: `ELZ_TAB026068BT_Cockpit_L0L_180803_V2.3.kbl`, no whitespace

**Comment by FlorianKirmaier** [comment]
@ryppo
Now I've been able to fix the problem. The fix will be released with the upcoming version 2018.1.9.

The file was deleted after some time by the internally used web framework.

A snapshot build is already available if you want to try it out. It's accessible when you set the JPro-Version to the following value: `2018.1.9-SNAPSHOT`

**Comment by ryppo** [comment]
@FlorianKirmaier 
Wow, must be a difficult debugging procedure.
Unfortunately the snapshot version does not work. I get this error:
`[INFO] --- jpro-maven-plugin:2018.1.9-SNAPSHOT:run (default-cli) @ crd-tools ---
[INFO] Waiting for jpro Server
Error: Could not find or load main class arg1
[ERROR] Server could not be started. Error-Code: 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------`
I get this in both:
- `mvn compile jpro:run`
- `mvn install jpro:release`, success. But executing `start.sh` afterwards provides the same error.

Don't worry. I can wait for the stable final version.

**Comment by FlorianKirmaier** [comment]
@ryppo
It's because of another bug, which is fixed in 2018.1.9.

Take a look at the change in the [HelloJPro-Maven](https://github.com/JPro-one/HelloJPro-Maven): [https://github.com/JPro-one/HelloJPro-Maven/commit/2d75d0c254ed50f8fd278b3ad07285b7aa91658c](https://github.com/JPro-one/HelloJPro-Maven/commit/2d75d0c254ed50f8fd278b3ad07285b7aa91658c)

**Comment by FlorianKirmaier** [comment]
@ryppo
It's from a test with font-weights in a test-build. You can ignore it.
