### ISSUE TITLE
How to copy custom libraries for `jproRelease` task of gradle project?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#111]
Hi there! I am using [jProOne](https://www.jpro.one/) & [JavafxMobilePlugin](https://github.com/javafxports/javafxmobile-plugin) in my project.

How can I copy from `desktopRuntime` of javafxmobile-plugin to final zip file build from `jproRelease` task for Gradle project?

I am using something like this code, for making executable jar file with all dependencies in `build\dist` folder e.g. 

```
startScripts {
    classpath += configurations.desktopRuntime
}

distZip {
    into("$applicationName/lib") {
        from configurations.desktopRuntime
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

def dependsDir = "${buildDir}/dist/lib/"
task copyDependencies(type: Copy) {
    from configurations.desktopRuntime
    into "${dependsDir}"
} 

task createJar(dependsOn: copyDependencies, type: Jar) {
    def libs = ""
    
    fileTree(dependsDir).visit {files -> 
    	libs += "lib/" + files.file.name + " "
    }
    
    manifest {
        attributes  'Implementation-Title': applicationName,
                    'Class-Path': libs,
                    'Main-Class': mainClassName
    }
    
    baseName = applicationName
    with jar
}

assemble.dependsOn(createJar)

task resourcesCopy() {
    doLast {
        copy {
            from "${buildDir}/libs"
            into "${buildDir}/dist"
        }
        file("${buildDir}/libs/" + applicationName + ".jar").delete()
        
        copy {
            from "${projectDir}/lib/logging.properties"
            into "${buildDir}/dist/lib"
        }
        
        mkdir "${buildDir}/dist/logs"
    }
}

createJar.finalizedBy(resourcesCopy)

sourceSets {
    main {
        resources {
            exclude '**/*.jrxml'
        }
    }	
}
```

I am not sure, how `jproRelease` task make it's final zip e.g. `build/distributions/HelloJPro-jpro.zip` file and copy it's dependencies to lib folder.

Any helps is much appreciated.

General Info
```
jpro-plugin-gradle:2019.2.7
jfxmobile-plugin:1.3.18
OS:Windows
Buid System:Gradle
```

**Comment by FlorianKirmaier** [comment]
The JavaFXMobile plugin is now deprecated and therefore no longer maintained for several years.
The GluonFX plugin is the replacement: https://github.com/gluonhq/gluonfx-gradle-plugin
If you are only using Desktop and JPro, I would recommend only use https://github.com/openjfx/javafx-gradle-plugin and the current JPro Plugin.

General speaking, creating a "fat-jar" with all the jars is general rather deprecated. and leads to various complicated issues. My recommendation would be to use something like https://badass-runtime-plugin.beryx.org/releases/latest/ , which allows you to create native installers for the Desktop.

The JProRelease Plugin takes the dependencies from the `runtime` configuration.
Because `desktopRuntime` is only defined by Gluon, JPro can't use it. I would recommend avoiding these configurations, which only work in the context of a specific Gradle plugin.

You can add additional files to the release zip with the following statements:
```
jpro {
  jproReleaseFiles << JProReleaseFile(new File("target/file3.dat"), "/data/")
}
```

I hope this helps you and leads you to a solution to your problem!

**Comment by ctoabidmaqbool** [comment]
@FlorianKirmaier Thanks for your solutions.

Actually I was seeking about some clean solutions / quick way to do solve this problem in jproPlugin. I can't use `gluonfx-gradle-plugin` because It's not yet fully functional in our case, e.g some of the libraries we are using is not yet works with this plugin. And another thing we are trying to make Android, Desktop & Web so it's currently too expansive process.

I have solve the problem using something like this code:

```
def jproAppName = applicationName.replaceAll("\\s", "").concat("App-jpro")

// Register new task replaceZip of type org.gradle.api.tasks.bundling.Zip.
tasks.register("replaceJproZip", Zip) {
    // Temporary name archive file to eSalesAnalystApp-temp.zip
    archiveBaseName = "${jproAppName}-temp"

    // Include the content of the original archive.
    from(zipTree("${buildDir}/distributions/${jproAppName}.zip")) {
        // But leave out the files we want to replace.
        exclude("${jproAppName}/libs/**")
    }

    // Add files with same name to replace.
    from("${buildDir}/libs") {
        into("${jproAppName}/libs")
    }
    into("${jproAppName}/libs") {
        from configurations.desktopRuntime
    }

    into("${jproAppName}") {
        File.createTempDir().with {
            def tmpLog = new File(absolutePath, 'logs')
            // println tmpLog.absolutePath
            tmpLog.mkdirs()
            from (absolutePath) {
                includeEmptyDirs = true
            }
        }
    }

    // As archives allow duplicate file names we want to fail
    // the build when that happens, because we want to replace
    // an existing file.
    duplicatesStrategy = "FAIL"

    doLast {
        // Delete orignal archive file created by jproRelease task e.g. eSalesAnalystApp-jpro.zip
        file("${buildDir}/distributions/${jproAppName}.zip").delete()

        // Rename custom archive file to orignal file name e.g. eSalesAnalystApp-jpro.zip
        ant.move(
                file: "${buildDir}/distributions/${jproAppName}-temp.zip",
                tofile: "${buildDir}/distributions/${jproAppName}.zip"
        )
    }
}

jproRelease.finalizedBy(replaceJproZip)
```

**Comment by FlorianKirmaier** [comment]
I think the issue is solved for now. If you need any further help, feel free to ask and make a new ticket.
