### ISSUE TITLE
Javafx dropdown boxes (sub-window) shows at wrong position in a specific case at jPro app.

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#116]
When I have set

`flowpaneCards.prefWrapLengthProperty().bind(stage.widthProperty());`

dropdown sub-windows shows at wrong positions in jPro Apps but in desktop view working fine.

![image](https://user-images.githubusercontent.com/10474725/146926052-70f96171-4d6b-45e0-883e-e0546566ecbf.png)

Here is a testing app:  https://github.com/Maqbool-Solutions-SMC-Pvt-Ltd/JPro-Orientation-Test/commit/d7fd6f5ee6aead047fb517b9e4b6fe580ff00baa

**Comment by FlorianKirmaier** [comment]
Thank you for reporting this! We will take a look.

**Comment by FlorianKirmaier** [comment]
Try out the latest SNAPSHOT version `2021.2.3-SNAPSHOT`, which should solve the problem.

**Comment by FlorianKirmaier** [comment]
I assume this works now for you, so I close the ticket.
