### ISSUE TITLE
javafx WebView

### ISSUE THREAD

**Issue by f-geo** [JPro-one/JPro-tickets#12]
Hello,

Cant load http://jpro.one in WebView.
The server say:
Connection refused by server

Br,

**Comment by FlorianKirmaier** [comment]
@f-geo
Strange, I've just tried it out, and it seems to work for me. It might be dependent of the JavaFX-Version? For my test, I was using the version `jdk1.8.0_181`. I think, also the smaller version-number 181 is relevant here.

But I must notice, that it contains several rendering-issues, which are either bugs in the WebView or JPro.

Which version were you using?

**Comment by f-geo** [comment]
1.8.0_191

**Comment by f-geo** [comment]
package fx;

import javafx.application.Application;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.concurrent.Worker;
import javafx.concurrent.Worker.State;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.ScrollPane;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
//  w  w  w.j av a2s  . c  o m
public class MainWebView extends Application {
  @Override
  public void start(final Stage stage) {
    stage.setWidth(1000);
    stage.setHeight(1000);
    //stage.setMaximized(true);
    Scene scene = new Scene(new Group());

    final WebView browser = new WebView();
    final WebEngine webEngine = browser.getEngine();

    ScrollPane scrollPane = new ScrollPane();
    scrollPane.setContent(browser);
    scrollPane.setFitToHeight(true);
    scrollPane.setFitToWidth(true);
    webEngine.getLoadWorker().stateProperty()
        .addListener(new ChangeListener<State>() {
          @Override
          public void changed(ObservableValue ov, State oldState, State newState) {

            if (newState == Worker.State.SUCCEEDED) {
              stage.setTitle(webEngine.getLocation());
            }

          }
        });
    webEngine.getLoadWorker().exceptionProperty().addListener(new ChangeListener<Throwable>() {
        @Override
        public void changed(ObservableValue<? extends Throwable> ov, Throwable t, Throwable t1) {
            t1.printStackTrace();
        }
    });
    String url = "https://jpro.one";
    //String url = "http://server.logicash.se/minkassadeb";
    webEngine.load(url);
    
    scene.setRoot(scrollPane);

    stage.setScene(scene);
    
    stage.show();
  }

  public static void main(String[] args) {
    launch(args);
  }
}

**Comment by FlorianKirmaier** [comment]
Strange, how does your code look like?

My working code looks like the following:
```
WebView wview = new WebView();
wview.getEngine().load("http://jpro.one");
wview.prefWH = (800,800);
```

**Comment by FlorianKirmaier** [comment]
It seems like the WebView doesn't handle the redirect from http to https very well.
Try changing the URL from `http://jpro.one` to `https://jpro.one`

**Comment by f-geo** [comment]
Did. It just hangs without the "connection refused" Exception
java.lang.Throwable: Connection refused by server
	at javafx.scene.web.WebEngine$LoadWorker.describeError(WebEngine.java:1467)

**Comment by FlorianKirmaier** [comment]
You are right, my last message is incorrect.
`https://jpro.one` doesn't work in general, also in the Browser.
`http://jpro.one`, `http://www.jpro.one` and `https://www.jpro.one` are working.
In your initial message, you were using another link as in the code. (http vs https)

This issue is neither related to JPro, nor to JavaFX, it's because of how the Server and the DNS are set up.

**Comment by f-geo** [comment]
Nope. webEngine result :SUCCEEDED but page is blank.
You are right the first problem was url gave Connection refused
Same code shows my vaadin page fine.

Try it with 1.8.0_191

**Comment by FlorianKirmaier** [comment]
Updated to 1.8.0_191 doesn't change the behavior for me.
The one link doesn't work, the rest works with some rendering issues.

**Comment by FlorianKirmaier** [comment]
Works with latest javafx version 17.0.1
