### ISSUE TITLE
jpro Responsive Screen issue on small devices / screen

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#123]
I have noted a responsiveness issue of jpro web controls e.g. jpro-Markdown-View on small devices / screen. Any why to solve it?

Top & Down page view on Large screen (desktop):
![image](https://user-images.githubusercontent.com/10474725/158742338-f8065e29-f5f4-48a7-8dfa-e4f3a17c65fe.png)
![image](https://user-images.githubusercontent.com/10474725/158742961-9a209c8d-ab07-47de-9406-49e31d1fe767.png)

Top & Down page view on Small Device (Android)
![image](https://user-images.githubusercontent.com/10474725/158742606-8fff8516-7ff2-42a7-b5a7-543406193877.png)
![image](https://user-images.githubusercontent.com/10474725/158742763-ba1e979d-8c81-4603-97c9-ad781c8d8235.png)

As you are noting in **Small Previous many of the page is cut off form top & bottom**.

I have create a small testing app to demonstrate this issue: 
https://github.com/Maqbool-Solutions-SMC-Pvt-Ltd/jPro-Responsive-Screen-Issue

Let me know any more info is needed!

**Comment by FlorianKirmaier** [comment]
Hi @ctoabidmaqbool 
Can you give me access to the test application?
I think it's a private repository, which is why I can not access it.

**Comment by ctoabidmaqbool** [comment]
@FlorianKirmaier Hi! I have change the repository type to public. Now you can check it now!

**Comment by FlorianKirmaier** [comment]
Very Interesting. This doesn't seem to be a JPro Bug, because it also happens when you run it as a desktop application.
So it's probably either in the markdown view or in JavaFX itself.

**Comment by ctoabidmaqbool** [comment]
> Very Interesting. This doesn't seem to be a JPro Bug, because it also happens when you run it as a desktop application. So it's probably either in the markdown view or in JavaFX itself.

Then I think, It's more likely issue of javafx. Because in my another app I am tying to achieve same thing with many labels inside vbox and same issue happens in jpro-web and javafx desktop too.
