### ISSUE TITLE
Smartphone virtual keyboard hides nodes

### ISSUE THREAD

**Issue by guirak** [JPro-one/JPro-tickets#137]
Hi Florian, 

When I click on a TextField in my JPRO app from a web browser in phone, the virtual keyboard appears and hide the field if it is in the bottom part of the screen.

There is no scene resize when the virtual keyboard appears. So I can't use a listener on the height to detect the virtual keyboard.

In a launch from an Android App, I have disabled the system virtual keyboard and I use KeyboardFX. When a field is focused, the virtual keyboard appears and the root pane translate vertically to permit the display of the field.

Is there a way with JPRO to do one of these things :
  - Activate a behavior similar to the one provided by KeyboardFX when the virtual keyboard appears.
  - Detect the opening of the virtual keyboard from phone : this will permit me to implements a behavior similar to KeyboardFX
  - Disable the phone virtual keyboard : this will permit me to enable the KeyboardFX instead 

Thank you.

**Comment by guirak** [comment]
Hi Florian, 

Please, can you give me a response for this issue ?

Thank you.

**Comment by FlorianKirmaier** [comment]
In general, the mobile keyboard is very "clumsy"

We could allow disabling the VirtualKeyboard in general.

And based on the other ticket, we should support the FX Robot to make KeyboardFX (or an adapted version) work.

So that would be the way to go.

**Comment by guirak** [comment]
Hi Florian,

If you can allow disabling the VirtualKeyboard, it will be perfect for me. We have planned to experiment the application for one of our customer at the end of May. Do you think, the feature can be available before this date ?

For KeyboardFX, it is working very well with the option  "jpro.reduceInputKeyBindings = false". I haven't fall in any problem for the moment. 

Thank you

**Comment by FlorianKirmaier** [comment]
Yes, that should be possible.
We will provide you with a build quite soon.
Do you, in general, don't use the standard keyboard, also for the web+desktop? (if web+desktop exist)

**Comment by guirak** [comment]
Hi Florian.
If you allow disabling the native VirtualKeyboard, I will make it always unavailable and use my custom keyboard with KeyboardFX as it is optimised and contains only the useful for the app.
So in this case, I will have 2 configurations that will be choosen with WebApi.isMobile : 
- In case of mobile the KeyboardFX pane is present at top level of the scene and any focus on a text field, text area, ... will display it.
- In case of desktop the KeyboardFX pane is not inserted in the scene.

**Comment by FlorianKirmaier** [comment]
Ok, I've added the option to disable the VirtualKeyboard.

From the Changelog:

Added the attribute "disableVirtualKeyboard" to the jpro tag. When set to true, the virtual keyboard is disabled.

You can use it like the following: `<jpro-tag disableVirtualkeyboard="true" .... />
Please test it, and give use some feedback, whether this works for you.



You can try it out with the version `2023.1.1-DISABLE-VKEYBOARD`
This is a stable version, which you can use for your next release.

**Comment by guirak** [comment]
Ok. Thank you. I will try to do the test today.

**Comment by guirak** [comment]
Hi Florian, maybe I'm doing something bad, it seems not working. 

I have put the tag in the index.html : 

`<jpro-app href="/app/mmione" fullscreen="true" disableVirtualkeyboard="true" ></jpro-app>`

It is right ? The virtual keyboard still appears in Android and Iphone with this.

Thank you.

**Comment by FlorianKirmaier** [comment]
I've noticed a small difference in the case. Can you try "disableVirtualKeyboard=true" (notice the uppercase K)
Maybe that's the problem.
Which version did you use?

**Comment by guirak** [comment]
Yes, I have seen this missing uppercase and I have yet tested without it. The keyboard is not disabled.
I have changed my version of JPRO to use 2023.1.1-DISABLE-VKEYBOARD.

Also, I have gradle cleaned my project to ensure I'm using this version...

**Comment by guirak** [comment]
Sorry ! I have done the test again and now it's working without changing anything. So maybe as well in Android and IPhone. 
So maybe something that wasn't cleaned correctly previously...

Thank you, I will do additional test to be sure it works on all configuration.

**Comment by FlorianKirmaier** [comment]
Yes, if you change something in the index.html, it's easy to forget to reload the page - because JPro itself does a whole reconnect (without reloading the index.html)

You can use this version for production.

**Comment by guirak** [comment]
Thank you Florian. 
Tested yesterday and no problem found.

**Comment by FlorianKirmaier** [comment]
Great, closing the ticket now.
