### ISSUE TITLE
Custom Loader Gif

### ISSUE THREAD

**Issue by timoreichen** [JPro-one/JPro-tickets#15]
It would be nice to customize the loading gif so it could be fit the colors of the application. Basically just allow to define a custom gif or any image within the index.html or jpro.conf. Maybe also with possible positioning. But centered would be a good start.

**Comment by timoreichen** [comment]
For example like this:
<jpro-app href="/app/main" loader="none" loaderUrl="/path/image.gif">

If loaderUrl is set, the customized image is used. If not set the loader-property is used.

**Comment by guptamitesh** [comment]
Too looking for some custom loader. Any update here?

**Comment by FlorianKirmaier** [comment]
Due to increased, we will add it to our next minor update.

**Comment by FlorianKirmaier** [comment]
With the version 2019.2.5-SNAPSHOT It's now possible to define an own loader based on a gif by setting `loaderURL="/your.gif"` in the JProTag.

**Comment by FlorianKirmaier** [comment]
Important note:
If you want to use your own loader, you should NOT set `loader="none"`. This will also disable your custom loader.
