### ISSUE TITLE
Cannot resolve one.jpro.jproutils:tree-showing:0.2.2.  (no/invalid pom)

### ISSUE THREAD

**Issue by Siedlerchr** [JPro-one/JPro-tickets#150]
I wanted to use gemsfx from Dirk Lemmerman and encountered this exception:

FAILURE: Build failed with an exception.

* What went wrong:
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve one.jpro.jproutils:tree-showing:0.2.2.
     Required by:
         project : > com.dlsc.gemsfx:gemsfx:1.72.0
      > Could not resolve one.jpro.jproutils:tree-showing:0.2.2.
         > Could not parse POM https://sandec.jfrog.io/ui/native/repo/one/jpro/jproutils/tree-showing/0.2.2/tree-showing-0.2.2.pom
            > The markup in the document preceding the root element must be well-formed.

**Comment by FlorianKirmaier** [comment]
Could not parse - interesting. 

Which build tool are you using, and which version?

**Comment by Siedlerchr** [comment]
I could resolve it now, it seems like I had the wrong url configured:

https://sandec.jfrog.io/ui/native/repo did not work
https://sandec.jfrog.io/artifactory/repo/ works

**Comment by FlorianKirmaier** [comment]
@Siedlerchr 
Great to hear!

From where did you get the wrong URL? Is it somewhere wrong documented?

**Comment by Siedlerchr** [comment]
Yes, I got the correct url  at first but when I opened it in my browser I got redirected. Seems like I then copied the browser url back to my file.
