### ISSUE TITLE
How to use CSSFX in JavaFx or jPro project?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#152]
@FlorianKirmaier Hi! CSSFX is vary nice library to auto reload CSS file in Javafx project. But how to use in Gradle Project? 

Many jPro projects are using CSSFX, but it looks like it's not working. How to start CSSFx to monitor CSS auto reloading?

Project using CSSFX, [jpro-routing](https://github.com/JPro-one/jpro-routing), [jpro-routing-sample](https://github.com/JPro-one/jpro-routing-sample), [markdown-javafx-renderer](https://github.com/JPro-one/markdown-javafx-renderer)

**Comment by ctoabidmaqbool** [comment]
I also try:

```
implementation "one.jpro:jpro-routing-core:0.15.0-SNAPSHOT"
implementation "one.jpro:jpro-routing-dev:0.15.0-SNAPSHOT"
implementation 'org.scenic-view:scenic-view:11.0.3-SNAPSHOT-FORK'
implementation "fr.brouillard.oss:cssfx:11.4.0"
```

```
return Route.empty()
      .and(get("/privacy", (r) -> {
          return new PrivacyPolicy();
      }))
      .filter(DevFilter.createDevFilter());
```

Which create DevFilter something like this:
![image](https://user-images.githubusercontent.com/10474725/233032390-49d9332b-6f9c-4536-b2ce-6ecb10a720e5.png)

When open ScenicView from this dev-filter, CSS auto reload also not working. However If I run external scenic-view then CSS auto reloads.

**Note:** My CSS files path is absolute too e.g. 
```
private static final String ABS_SRC_PATH = "file:///D:/NetBeansProjects/MyApp/src/main/resources/";
private static final String MAIN_CSS= ABS_SRC_PATH + "assets/css/Maincss.css";
root.getStylesheets().add(MAIN_CSS);
```

**Comment by ctoabidmaqbool** [comment]
Okay! I have **solved** the above issue in `jPro with Routing` project by simply following below method.

In `gradle.buld` file:
```
implementation "one.jpro:jpro-routing-core:0.15.0-SNAPSHOT"
```

Add `Routing filter`:
```
.filter(DevFilter.createDevFilter());
```

And by using correct Absolute URL by using `toExternalForm() method.
```
private static final String ABS_SRC_PATH = "/";
public static final String MAIN_STYLE = ABS_SRC_PATH + "assets/css/Maincss.css";

root.getStylesheets().add(getClass().getResource(MAIN_STYLE).toExternalForm());
```

So the main thing was the wrong way of using Absolute path of CSS files.

**Comment by FlorianKirmaier** [comment]
Great, what did you provide before?
CSSFX should reload it also with a not absolute URL, but there might be a bug.
I guess you could create a ticket at CSSFX, with an example of what works, and doesn't work.

**Comment by ctoabidmaqbool** [comment]
> Great, what did you provide before?
> CSSFX should reload it also with a not absolute URL, but there might be a bug.
> I guess you could create a ticket at CSSFX, with an example of what works, and doesn't work.

Okey! I will try to issue at CSSFX repo too.
