### ISSUE TITLE
File download with loadbalancer in a docker stack

### ISSUE THREAD

**Issue by bc-hvtk** [JPro-one/JPro-tickets#153]
Hi,

I'm having issue with the loadbalancer. If I run the client directly, the problem does not appear, but with loadbalancer:
![2023-04-24 12_43_50-Window](https://user-images.githubusercontent.com/129406419/233974440-d781c24d-9940-4af8-9377-6096f049c387.png)

I tried different folders for the temp files but nothing seems to be ok. I also tried to rename the file extension to .png and with this trick I have been able to download the file. If there any application.properties I need to change to allow different ContentTypes to make it work ? Or do I have to do something particular?

I'm using this one for download: WebAPI.getWebAPI(getScene()).downloadURL(f.toURI().toURL());
(f being the file. It exists on the server)

Thanks in advance for your help

**Comment by FlorianKirmaier** [comment]
Thank you for the bugreport! This seems to be a bug in the Loadbalancer / JPro, we will investigate it.
