### ISSUE TITLE
ListView scrolling on mobile.

### ISSUE THREAD

**Issue by guirak** [JPro-one/JPro-tickets#154]
Hi Florian,

On mobile, ListView doesn't scroll correctly. 
I can solve completely the problem making the ListCells transparent but sometimes I need interactions on the content of the ListCell.
In this case, if I put, for example, a VBox in the ListCell and I configure a custom interaction on the ListCell to manage myself the mouse pressed, mouse released, I can reduce strongly the bad scrolling effect but it doesn't solve completely as sometimes dragging the finger doesn't trigger the scroll.

I think there is some MOUSE_PRESSED or MOUSE_CLICKED event triggered by the ListCell that block the propagation of the event to the ListVIew
Is there a specific configuration property to set to have the ListView scrolling correctly on mobile ?

Thank you.

**Comment by FlorianKirmaier** [comment]
I can't confirm the issue.
I can scroll a ListView simply by touch.

It works for me with standard ListCells.

Are you consuming/modifying the events?
We are basically doing the same as JavaFX does with every touch event on touchdevices / mobile.

**Comment by guirak** [comment]
Hi Florian, I have isolated a listview with custom cell and it's working well in JPRO. 
Sorry, as I was having the problem since the beginning and never encounter this problem in native, I was persuaded that is due to the use of touch instead of mouse wheel in mobile. 

I can close the ticket.

**Comment by guirak** [comment]
I have isolated the cause of the problem. The problem is caused by this style in CSS :

```
.list-view > .virtual-flow > .clipped-container > .sheet > .list-cell:filled:hover{
    -fx-background-color: -fx-alt2-background-color;
}
```

If I remove it, I haven't the problem. 
This style has no interest on mobile and is useful only for desktop. So I will activate it only on desktop. 

Thank you
