### ISSUE TITLE
WebAPI FileUploader work just once and stop upload file

### ISSUE THREAD

**Issue by evolutique** [JPro-one/JPro-tickets#156]
JPro Version : 2023.1.0
Java Version : jdk_11.0.14
Browser+Version : chrome 112.0.5615.140
Your Operating System : Windows
Are you starting the appliation with maven/gradle or did you use "jproRelease" from the plugins : maven

I create a component(FileHandler) like in sample and it work well. If i change the current view and come back then the button have no reaction anymore and no filebrowser appear. No exception is  logged in any jpro.*.log

For info : when i change the view that load another FMXL via FXMLLoader but i dont think its the problem.

**Comment by FlorianKirmaier** [comment]
Interesting, can you provide a sample?
On our online page: https://www.jfx-ensemble.com/sample/jpro-samples/FileHandlerApp
it works, when test it, got to another page, go back, then it still works

**Comment by FlorianKirmaier** [comment]
I think it's fixed. But if you find a reproducible sample, feel free to reopen it or create a new ticket.
