### ISSUE TITLE
File upload with loadbalancer in a docker stack

### ISSUE THREAD

**Issue by bc-hvtk** [JPro-one/JPro-tickets#158]
Hi,

I'm having issue with file upload virtual client side.
Unfortunately I don't have much info about the issue beside that:
![2023-05-22 19_09_11-Window](https://github.com/JPro-one/JPro-tickets/assets/129406419/fb12d671-afab-47fb-beee-980f882ea7a6)

I already tried:
![image](https://github.com/JPro-one/JPro-tickets/assets/129406419/8021efd9-c178-4370-9a78-d253de8ca83c)

From docker stack I get that:
![image](https://github.com/JPro-one/JPro-tickets/assets/129406419/80d20d2a-6b84-4b2e-b1b5-c84c2761d908)

Even with -D.. for loadbalancer and still have the same error.
Any chance you encountered that before?
Thanks in advance.
Regards

**Comment by FlorianKirmaier** [comment]
Thank you for the bugreport!
We will investigate this, and ensure that the upload will work.
And we will also look into your other ticket: #153

Sorry for the delay, but we will now work on the load balancer anyways, which will end up with many new features.

**Comment by bc-hvtk** [comment]
Thanks for your answer. Do you have any approximate timing on when I could test the new snapshot version?
I also experienced the same as https://github.com/JPro-one/JPro-tickets/issues/156 not in a loadbalancer environment.
Version 2023.1.0, openjdk 11.0.7.12

**Comment by FlorianKirmaier** [comment]
@bc-hvtk 
Can you write more about your setup?
Are you using docker with some other tools? Like Kubernetes? Maybe a more complex docker-compose setup?

On plain docker, upload/download works for me!

I think some part of your setup doesn't support WebSocket - but this would imply that the whole application doesn't work. So it's still a bit strange.

**Comment by FlorianKirmaier** [comment]
Quick update, i can confirm that the fileupload doesn't work when using the loadbalancer (independent of docker)
We are looking into it, and tell you, when we have a fix available.

**Comment by FlorianKirmaier** [comment]
Minor update - we found the bug and fixed the bug.
We are further improving the load balancer to add some other required features.
After that, we will create a new JPro / Loadbalancer release containing the fix.
If you need the fix earlier, feel free to contact us by email.
