### ISSUE TITLE
JPro Status : timeRunning

### ISSUE THREAD

**Issue by guirak** [JPro-one/JPro-tickets#163]
Hi Florian, 

When retrieving the status of the jpro server, we have the following for example : 

  "Start time" : "Thu Jun 29 07:51:54 UTC 2023",
  "Time running" : "1 days 01:53:29.399",
  "Instances created" : 0,
  "Instances active" : 0,
  
 What is the format of the Time running duration  ? We can parse a LocalTime as HH:mm:ss.SSS for the duration in the day but for the days, it's always days or it become weeks, months, years ?  
 
 Thank you ?

**Comment by besidev** [comment]
Hi @guirak ,

Since release of JPro version `2023.2.2` the `Time running` duration format is now [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601), which is pretty standard across multiple platforms and languages. 

Thank you.

**Comment by guirak** [comment]
Hi besidev, 

Yes, thank you. I have tested this release last week. It's perfect.
