### ISSUE TITLE
Support for different environments

### ISSUE THREAD

**Issue by ryppo** [JPro-one/JPro-tickets#17]
I'd like to dynamically support different environments for the jpro hosted application.
Use case: You want to deploy the application, without active configuration for the specific environment (test, dev, production).
As `Application.getParameters()` is not supported, I investigate for another solution.
Example ideas:
- Parameter for the shell script, like `./bin/start.sh myParameterString`
- Set a jre environment variable on start of the shell script.

--> Is there any solution available or at the horizont?

**Comment by FlorianKirmaier** [comment]
I think, what you plan to do, is allready supported in JPro.
You can allready do the following `./bin/start.sh -Dconfig.file=<pathtofile>`
In the code, you can read it out like the following:
```
System.getProperty("config.file");
```

But note, that it has to be an environmental variable, which get be read with getProperty. It can't be a generic String argument.

We might support `Application.getParameters` in the near future, but it would be used, to parameterize a session.

**Comment by ryppo** [comment]
Thx. This is the feature we use to be as flexbile as we need. 
Issue solved.
