### ISSUE TITLE
Could not find method jproOnly()!

### ISSUE THREAD

**Issue by ctoabidmaqbool1** [JPro-one/JPro-tickets#170]
I was trying to add depedency for jpro only in gradle.build file e.g. As mentioned here https://www.jpro.one/docs/current/2.2/CONFIGURING_JPRO

```
implementation 'com.jfoenix:jfoenix:9.0.10'
jproOnly 'org.rationalityfrontline.workaround:jfoenix:21.0.0'
```

But it's was showing error:
```
> Could not find method jproOnly() for arguments [org.rationalityfrontline.workaround:jfoenix:21.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Gradle** `7.3.3`
**Jdk** `17.0.10`

**Comment by ctoabidmaqbool1** [comment]
@FlorianKirmaier Any solutions yet?

e.g. jproOnly in gradle!

**Comment by FlorianKirmaier** [comment]
Could you let me know if you applied the JPro Plugin before declaring the dependency?

On a quick test, it worked for me:
```
dependencies {
    jproOnly group: 'org.json', name: 'json', version: '20231013'
}
```

**Comment by ctoabidmaqbool1** [comment]
@FlorianKirmaier I have applied my JPro Plugin after dependency!

I will try to add it before dependency and check it latter too!

**Comment by FlorianKirmaier** [comment]
I assume it works now. So Im closing the ticket.
