### ISSUE TITLE
Editable ComboBox: Editor not working with jpro

### ISSUE THREAD

**Issue by elkejava** [JPro-one/JPro-tickets#172]
The Editor of editable ComboBox does only react once when it is focused by loading of the jpro website. Every other editable Combo's Editor does not allow writing, also the first one at going back.
Verified on Linux Mint 20 (Chrome, FF) and Windows 10 (Chrome, FF, Edge), browsers in newest version
javafx 18 with
gradle 7.3.3, java 11,  jpro 2022.1.3 (versions in production)
and
gradle 8.5, java 17, jpro 2024.1.0  (versions of newest hellojpro, used in attached sample)
[240306FilterComboSample.zip](https://github.com/JPro-one/JPro-Tickets/files/14546576/240306FilterComboSample.zip)

**Comment by FlorianKirmaier** [comment]
Thank you for the bug report!
It seems like something is going wrong when switching from 1 ComboBox to another.
It does seem to work when another TextField is focused in between.

We will take a look!

**Comment by FlorianKirmaier** [comment]
The issue happened when switching from one ComboBox to another.

Please test the version `2024.1.1-SNAPSHOT`
It should work with this version.

We'll probably make a stable release on some day of March.

**Comment by elkejava** [comment]
That is why it took so much time to identify the issue: i always switched between different controls, so the problem seemed to be arbitrary (or caused by my custom FilterComboBox Implementation).
I tried now with 2024.1.1-SNAPSHOT as well in my sample as in my application, it worked all fine.

**Comment by FlorianKirmaier** [comment]
This happened with every ComboBox, or more specifically, with every Control, which has an internal TextField, which focus state was "simulated" (because the ComboBox has the actual focus)
No one reported this, probably because it's hard to find out what's going on.
So thank you for the bug report!
I'm closing the ticket.

**Comment by elkejava** [comment]
Thank you, Florian. I am happy to hear that I could help to identify and solve an issue which was more basic as I ever thought. Will there be a notification about the new stable release on this way?

**Comment by elkejava** [comment]
SOLVED
It seems that the problem ist  not yet totally solved. In case that a value is selected at start, the Combo may be not responsible unless I focus some other part of the GUI and back. I will try to catch this in a sample.

-> could be solved in my implementation.

**Comment by besidev** [comment]
Hello @elkejava,

Today we are providing a new milestone release `2024.1.1-M1` for JPro (added support for JavaFX 22 and some other features and bugfixes). Please give it a try and let us know. Thanks.

**Comment by elkejava** [comment]
Hi Besmir

Is this the new stable version Florian Kirmaier announced (as I do not yet see it on jpro.one?

Thanks, Elke


Von: Besmir Beqiri ***@***.***>
Gesendet: Dienstag, 9. April 2024 16:43
An: JPro-one/JPro-Tickets ***@***.***>
Cc: Elke Hofmann ***@***.***>; Mention ***@***.***>
Betreff: Re: [JPro-one/JPro-Tickets] Editable ComboBox: Editor not working with jpro (Issue #172)


Hello @elkejava<https://github.com/elkejava>,

Today we are providing a new milestone release 2024.1.1-M1 for JPro (added support for JavaFX 22 and some other features and bugfixes). Please give it a try and let us know. Thanks.

-

**Comment by besidev** [comment]
It's a milestone release of the latest build, but not yet a stable release. Probably later this month we will make a stable release.
