### ISSUE TITLE
Certain keycodes show as Unknown Keycode

### ISSUE THREAD

**Issue by nyzzik** [JPro-one/JPro-tickets#177]
**JPro Version:** 2024.1.0
**Java Version:** 21.0.2
**Browser+Version:** FireFox 127.0 + Microsoft Edge 126.0.2592.61
**Your Operating System:** Windows 11
**Are you starting the appliation with maven/gradle or did you use "jproRelease" from the plugins?** I have tried using both and the same results are shown. 

When trying to check for keyboard input, certain keys do not register properly even though they do when the program is being run as a desktop application. 

Keys Affected:
\- (MINUS, not SUBTRACT) Displays Unknown Keycode: 173
[   Displays Unknown Keycode: 219
]   Displays Unknown Keycode: 221
\   Displays Unknown Keycode: 220
,   Displays Unknown Keycode: 188
.   Displays Unknown Keycode: 190
/   Displays Unknown Keycode: 191
Enter (Enter does not register at all, not even as an Unknown Keycode despite registering fine in JavaFX)

**Comment by FlorianKirmaier** [comment]
Thank you for the feedback.
Do you have a usecase, where this is causing problems?

**Comment by FlorianKirmaier** [comment]
Thank you for the feedback.
Do you have a use case where this is causing problems?
Or are you just worried about the logging messages?

The KeyCodes in JavaFX are messy, and in relation to the web, they are even worse.
We'll probably have to change, how this is solved in JPro.

But TextInput should work in general, and hotkeys should also work in general.

**Comment by nyzzik** [comment]
Trying to create any hotkeys with the keys that I listed did not seem to work at all. I was adding an accelerator to a button and provided the KeyCombination that used minus and it never triggered.

**Comment by FlorianKirmaier** [comment]
Can you provide
a small snippet of a KeyCombination which does not work? (Code)

**Comment by nyzzik** [comment]
```java
DlgScene.getAccelerators().put(new KeyCodeCombination(KeyCode.MINUS),()->{
			System.out.println("Here");
			nextBtn.fire();
		});
```

This code works fine when running as a normal desktop application but not when running through the browser.

**Comment by nyzzik** [comment]
I think it may have something to do with using a US English keyboard

**Comment by FlorianKirmaier** [comment]
Quick Update: we are working on it.

**Comment by FlorianKirmaier** [comment]
Can you test the version `2024.2.2-SNAPSHOT` ?
It should now work much more reliably.

**Comment by nyzzik** [comment]
Yes, it works perfectly now, thank you for the help.

**Comment by FlorianKirmaier** [comment]
Nice
