### ISSUE TITLE
BarCharts graphic is missing

### ISSUE THREAD

**Issue by KniKnaKnorke** [JPro-one/JPro-tickets#18]
The PieChart element in JavaFX got some rendering problems while showing in web browser.
Other chart elements are working fine.
Simple sample application and screenshot are in the attachments.
[Fx_PieChart_Tester.zip](https://github.com/JPro-one/JPro-tickets/files/3194883/Fx_PieChart_Tester.zip)

**Comment by FlorianKirmaier** [comment]
@KniKnaKnorke
Thank you for the bug report.
We've been able to reproduce and fix the problem.
The fix will be released with the next major-release 2019.1.0, which will be released very soon.

**Comment by FlorianKirmaier** [comment]
@KniKnaKnorke The fix is now released. :)
