### ISSUE TITLE
JPro Screensharing not working on 2024.3.0

### ISSUE THREAD

**Issue by nyzzik** [JPro-one/JPro-tickets#183]
I recently updated my jpro version in my project to use 2024.3.0 however when I try to run the application i get an error saying 'The requested application "!myApp" does not exist!' I double checked to make sure that my jpro.conf has the exact name "myApp" defined and it does. If i removed the '!' from the index.html file, the application loads fine. Running it on version 2024.1.0, everything loads fine and the application shares among users properly.

**Comment by FlorianKirmaier** [comment]
Hi,
Thank you for mentioning this!

We forgot to update the Documentation after changing the syntax slightly.
We've updated it now.
Now, you have to use: `myApp?singleton=true`instead of "!myApp"
The "!" was causing some problems was it wasn't really standard conform.

Florian
