### ISSUE TITLE
Configuration for SSL

### ISSUE THREAD

**Issue by DeanWookey** [JPro-one/JPro-tickets#26]
I see the JPro site and demos all use SSL, and SSL is mentioned on the Deploying JPro page:

> For production it is highly recommended to use SSL. Why is this important? Because, some time proxies manipulate the traffic stream, and this would otherwise break the support of websockets.

Is there information somewhere on how to configure JPro to use SSL?

**Comment by FlorianKirmaier** [comment]
On our documentation, we describe how to configure Linux for JPro.
It also explains how to configure SSL.

https://www.jpro.one/?page=docs/current/2.7/PREPARING_LINUX_FOR_JPRO

I can also recommend let's encrypt for obtaining an SSL-certificate for free:
https://letsencrypt.org/

**Comment by DeanWookey** [comment]
Thanks, that's probably the one page I didn't look at. I had imagined it was part of the jpro conf, but it makes sense.
