### ISSUE TITLE
Not sure how to get admin pages to work

### ISSUE THREAD

**Issue by vewert** [JPro-one/JPro-tickets#30]
I wanted to try out viewing status and logs when running on a server. In jpro.conf I set up `adminUsername` and `adminPassword`, but when I try to access /status, etc. it says: `Please set username and password in the jpro.conf to access this page in production!`

This is the content of my jpro.conf:

```
//jpro apps
jpro.applications {
  "hellojpro2" = com.jpro.hellojpro.HelloJProFXML
}

adminUsername = "pass"
adminPassword = "word"
jpro.preventSystemExit = false
```

Maybe my syntax for this is incorrect??

Notes: Used jproRelease and am running on a Linux server, using Java 11.0.4

Thanks for your help.

**Comment by FlorianKirmaier** [comment]
Thank you for asking. The documentation wasn't very clear about it.

We've just updated the [updated the JPro documentation](http://localhost:8083/?page=docs/current/2.2/CONFIGURING_JPRO), to make it clear how it es configured.

It should look like the follwing:
```
jpro.adminUsername = "admin"
jpro.adminPassword = "secret"
```

**Comment by vewert** [comment]
Great, that worked!

Thanks for the help.
