### ISSUE TITLE
Deployment to Cloud Server

### ISSUE THREAD

**Issue by vewert** [JPro-one/JPro-tickets#31]
I'm just wondering, is there a way to deploy/run JPro applications on a Cloud server, such as Amazon AWS, Google App Engine, etc.? If so, how would that be done?

Thanks for your help,
Victor

**Comment by FlorianKirmaier** [comment]
Our homepage https://www.jpro.one/ is hosted on AWS. We usually use AWS for our projects.
Take a look at our homepage, on how to prepare Linux for JPro: https://www.jpro.one/?page=docs/current/2.7/PREPARING_LINUX_FOR_JPRO
