### ISSUE TITLE
Run modularized application with JPro

### ISSUE THREAD

**Issue by michihausheer** [JPro-one/JPro-tickets#33]
Hi!

Is it possible that JPro apps cannot use Java 9 modules and services currently? 
When I run my app with JPro, it throws an exception when trying to load a service through the ServiceLoader API.
I'm using a Gradle build. Tried adding "--add-modules" to jpro JVMArgs but then jProRun task says: 
"Unrecognized option: --add-modules javafx.fxml,javafx.controls 
Error: Could not create the Java Virtual Machine."

If it is possible, could you post a sample of a modularized application?

Thx, Cheers
Michi

**Comment by FlorianKirmaier** [comment]
Thank you for the ticket.

Can you give us a sample of what you try to do with the ServiceAPI which is not working?
This would help us to provide a solution for your requirements.

Our [HelloWorld](https://github.com/JPro-one/HelloJPro) works with Java11, but it might be it's not using the module system in the recommended way.

Florian

**Comment by michihausheer** [comment]
Hi Florian

In a simple controller, I try to load a service like this:
```
  @FXML 
  public final void initialize() {  
        addressService = AddressService.get();       
  }
```
The AddressService is an interface which is implemented in a different module located in a different JAR that I include via lib. 
```
public interface AddressService {  
   static AddressService get() {  
       return ServiceLoader.load(AddressService.class).findFirst().get();   
   }  
   AddressListItems listAddresses();  
}
```
When I run this it fails with a NoSuchElement exception when it tries to call the get(). 

> javafx.fxml.LoadException:
file:/C:/NetBeans/JPro/libs/www3.ui.javafx.jar!/com/opus/ww3/ui/Main.fxml

The second module provides the service, and the application runs fine without JPro.

Thx, cheers
Michi

**Comment by michihausheer** [comment]
Hi Florian

My project is based on the hello world, and I get it running through "gradlew run".
But "gradlew jProRun" claims it doesn't know the --add-modules option, as I stated in my first post.
Do you set a different source compatibility int that task or something?
Not sure if that could cause the JVM option to be not recognized...

Do you have an update?

Thx, cheers
Michi

**Comment by FlorianKirmaier** [comment]
The issue was resolved in private emails.
for reference, the modules are now configured like the following:
```
 JVMArgs << '--module-path'
 JVMArgs << 'libs'
 JVMArgs << '--add-modules'
 JVMArgs << 'www3.app.main,ww3.domain.address,ww3.persistence.address,tomea.core'
```
