### ISSUE TITLE
Setting jpro attributes without embedding into webpage

### ISSUE THREAD

**Issue by jasons2000** [JPro-one/JPro-tickets#37]
How can you override attributes like fxContextMenu without having to embed my jpro app inside a HTML page?

**Comment by FlorianKirmaier** [comment]
you can define your own index.html as resource in `resources/jpro/html/index.html`.
When this file is set, the jpro-server uses this file by default.

**Comment by jasons2000** [comment]
sorry, i changed the misleading title, can I set the fxContextMenu without using a HTML page?

**Comment by FlorianKirmaier** [comment]
No, currently you can only set this property in the HTML-page.

**Comment by FlorianKirmaier** [comment]
Closing the ticket, because the question is answered.
