### ISSUE TITLE
Will you support copy (as in copy and paste)?

### ISSUE THREAD

**Issue by jasons2000** [JPro-one/JPro-tickets#38]
Will you support copy (as in copy and paste)?

**Comment by FlorianKirmaier** [comment]
JPro supports copy paste.
You can copy code from JPro and paste it somewhere else, and you can copy text from somewhere else into JPro.
A limitation is, that you can not access the Clipboard directly.

**Comment by jasons2000** [comment]
OK, so you can't copy from JPro to the system clipboard, I presume that there is no intention to provide this feature, given that you have closed this ticket?

**Comment by FlorianKirmaier** [comment]
Im not sure, what you think is not supported. There is another ticket, about the same topic: https://github.com/JPro-one/JPro-tickets/issues/9
