### ISSUE TITLE
TypeError using Java 11

### ISSUE THREAD

**Issue by ryppo** [JPro-one/JPro-tickets#39]
Hi, in some case I receive this error:
`[error] com.jpro.JS - received msg: Unexpected exception: TypeError: Cannot read property 'M' of null`

My configuration is:
* JPro 2019.1.3
* JPro Maven Plugin 2019.1.3
* OpenJDK 11.0.1
* JavaFX 11

What is the impact, please? And can I avoid it?
Thank you in advance.

**Comment by FlorianKirmaier** [comment]
It's an NullpointerException in the javascript client.
Do you know when it happens? Does it happen on all browser?
When we can reproduce it, it should be easy to fix in JPro.

**Comment by ryppo** [comment]
Thank you. Your intention provides the proper direction. It was my fault to call a UI refreshment at the wrong position.
This issue can be closed.
:thumbsup:

**Comment by FlorianKirmaier** [comment]
Great. : )
