### ISSUE TITLE
Uploading larger files is not working when hosted in Ubuntu server in aws

### ISSUE THREAD

**Issue by Sreeharshareddy298** [JPro-one/JPro-tickets#43]
While trying to upload files larger than 1MB using WebAPI.FileUploader.
No error is seen. But, when the progress is completed to 100%, the value of  fileHandler.getUploadedFile() is returning null.

Some sample code here - 

`WebAPI.FileUploader fileHandler = getWebAPI().makeFileUploadNode(loadButton);

            fileHandler.setSelectFileOnClick(true);
            fileHandler.setSelectFileOnDrop(true);
            fileHandler.setOnFileSelected((file) -> {
                fileHandler.uploadFile();
            });
            fileHandler.uploadedFileProperty().addListener((observable, oldValue, newValue) -> {
                 File f = newValue;
            });
`

The value of `f` is coming to be null, if uploaded file sizes are >1MB.

While if I run it locally using **jproRun**, it seems fine and it is uploading better. But in release build, buiilt using **jproRelease**, its not working for larger size files.

**Comment by FlorianKirmaier** [comment]
Hi @Sreeharshareddy298
We are regulary uploading larger files through the WebAPI on an ubuntu server.
Are u using Nginx or another proxy? They might also block too large files.
If so, can you try it without any proxy in between the client and the server?

**Comment by Sreeharshareddy298** [comment]
@FlorianKirmaier Got it. Changing the settings in Nginx helped and it is working as expected.
The following config helped us

`server {
  .....
  client_max_body_size 100M;
 .....
  location / {
    proxy_pass http://jpro;
  }
}
`
