### ISSUE TITLE
TitledPane arrow button issue in WebVersion(Issue is in JPro: 2019.2.2 and not found in JPro: 2019.2.1)

### ISSUE THREAD

**Issue by jigarjigjig** [JPro-one/JPro-tickets#45]
Due the svg size of arrow button( 300 * 150) in TitledPane, upload node button doesn't work in WebVersion.
(i.e. WebAPI.getWebAPI(scene).makeFileUploadNode(button) )
Issue in JPro: 2019.2.2 and  not found in JPro: 2019.2.1

<img width="473" alt="Screenshot 2020-03-26 at 7 19 47 PM" src="https://user-images.githubusercontent.com/39264263/77655051-e4f18600-6f97-11ea-824e-12948e0c5445.png">
<img width="470" alt="Screenshot 2020-03-26 at 7 20 46 PM" src="https://user-images.githubusercontent.com/39264263/77655054-e58a1c80-6f97-11ea-965f-46c8efdbb0ba.png">
<img width="474" alt="Screenshot 2020-03-26 at 7 19 54 PM" src="https://user-images.githubusercontent.com/39264263/77655061-e6bb4980-6f97-11ea-863e-67baeb5ecc81.png">
<img width="474" alt="Screenshot 2020-03-26 at 7 19 16 PM" src="https://user-images.githubusercontent.com/39264263/77655068-eb7ffd80-6f97-11ea-8cdf-6dfe3b6b10a0.png">

**Comment by FlorianKirmaier** [comment]
Sorry, we kinda missed the ticket. 
Is it still relevant? 
There have been various fixes related to mouse-input.

**Comment by jigarjigjig** [comment]
@FlorianKirmaier This issue now not seen in last version of JPRO.
