### ISSUE TITLE
MSProject demo: tree table rows disappear

### ISSUE THREAD

**Issue by dlemmermann** [JPro-one/JPro-tickets#46]
On Chrome: after collapsing a row / task inside the treatable view all rows disappear.

![image003](https://user-images.githubusercontent.com/9534301/80217256-afe05e00-863f-11ea-9697-a9dcaf2de3dd.png)

**Comment by dlemmermann** [comment]
fyi: this does not happen when I run locally

**Comment by FlorianKirmaier** [comment]
fixed - it was caused by a wrong configuration of the demo-server.
