### ISSUE TITLE
MSProject demo: canvas do not get drawn when using Edge

### ISSUE THREAD

**Issue by dlemmermann** [JPro-one/JPro-tickets#47]
When running in Edge the canvases do not seem to get rendered at all.

![image004](https://user-images.githubusercontent.com/9534301/80217419-f03fdc00-863f-11ea-8708-c4a6f1989dde.png)

In the screenshot one can also see that the timeline reaches into the column header area of the tree table view.

**Comment by FlorianKirmaier** [comment]
Fixed - it will work with the next release 2019.2.4 by default.
