### ISSUE TITLE
How to improve scroll performace and make use of "nativescrolling = true"

### ISSUE THREAD

**Issue by jigarjigjig** [JPro-one/JPro-tickets#63]
Can anyone share an example for using "nativescrolling = true" which make use of browser scrolling as mentioned in jpro document  instead of jpro scrolling which is very slow?.

**Comment by jigarjigjig** [comment]
We tried as suggested in documents and that does not seems to be working.

**Comment by FlorianKirmaier** [comment]
You might also have to set fxHeight="true".
We will add an example do out sample project: https://github.com/JPro-one/JPro-Samples
This will make the app to a scrollable webpage, like jpro.one. If you have inner scroll panes then they will still behave the same.
A common cause of slow scrolling is also a very big scenegraph. Using lazy containers like ListView or TableView might improve this for big datasets.

**Comment by jigarjigjig** [comment]
Thanks an example will be much helpful.
@FlorianKirmaier  Locally scroll works smooth. But when same hosted to remote server scroll becomes heavy.

**Comment by FlorianKirmaier** [comment]
In this case it's related to latency.
Usually, it shouldn't be too bad, unless the i-net is quite slow.
native-scrolling should fix the problem.

**Comment by guptamitesh** [comment]
We too are experiencing slow scrolling seems it is due to network latency only, an example for native scrolling would help us @FlorianKirmaier 
Thanks.

**Comment by FlorianKirmaier** [comment]
We've added 2 samples to our sample-collection - `native-scrolling` and `website`: https://github.com/JPro-one/JPro-Samples
