### ISSUE TITLE
Website -> Doc all Codeblocks are white font on white background

### ISSUE THREAD

**Issue by og0815** [JPro-one/JPro-tickets#71]
On the Homepage of jpro.one under the section Doc all code blocks are white font color on white background.
OS Debian 10, all Browsers. 

![Bildschirmfoto vom 2020-08-10 17-49-18](https://user-images.githubusercontent.com/1500216/89802693-1bd4cc80-db32-11ea-877f-c32a50d022f7.png)

**Comment by FlorianKirmaier** [comment]
Thank you for reporting it!
Fix is on the way.

**Comment by FlorianKirmaier** [comment]
Thank you for reporting! 
Probably 99% of the people who have seen this, didn't mention it anywhere.
It should be working now!
