### ISSUE TITLE
How to secure the websocket channel?

### ISSUE THREAD

**Issue by samyc1201** [JPro-one/JPro-tickets#76]
I given a try on JPro maven project, it is running fine. I am checking around whether it is suitable to work as a simple Java backend. So I am thinking like how to handle its authentication and other aspects as well. 

One thing of my concern is, the websocket channel is not secure, as I see that it is using `ws://` from chrome debugger. Is it because I am running it in local host? Are we able to configure it as secure channel?

**Comment by FlorianKirmaier** [comment]
Yes, you can use JPro with SSL.
We usually use Nginx as a proxy to support SSL.
Check out our documentation for more details: https://www.jpro.one/?page=docs/current/2.7/PREPARING_LINUX_FOR_JPRO

**Comment by samyc1201** [comment]
alright thanks, I miss that part!
