### ISSUE TITLE
Unable to resolve class JProReleaseFile in build.gradle

### ISSUE THREAD

**Issue by pl4nty** [JPro-one/JPro-tickets#78]
Running `gradlew jproRelease` or `gradlew jproRun` with jproReleaseFiles [as in the docs](https://www.jpro.one/?page=docs/current/2.2/CONFIGURING_JPRO) gives `Unable to resolve class JProReleaseFile in build.gradle` with the following jpro config in `build.gradle`:
```
jpro {
  port = 80                         // The web-socket app to use.
  JVMArgs << '-Xmx1000m'              // Lets set the memory for the JPro-Server
  jproReleaseFiles << new JProReleaseFile("interactive.sh", "/bin/")
}
```

JPro Version: 2019.2.7
Java Version: 13.0.2
Browser+Version: N/A
Your Operating System: Ubuntu and Windows

**Comment by FlorianKirmaier** [comment]
Thank you for the report!
This is indeed an error in the documentation.
It should look like the following
```
  jproReleaseFiles << JProReleaseFile(new File("target/file1.dat"), "/data/newname1.dat")
  jproReleaseFiles << JProReleaseFile(new File("target/file2.dat"), "/data/newname2.dat")
```
We've updated the documentation on the website.

Can you confirm it's working this way?

**Comment by pl4nty** [comment]
Thanks, that works perfectly! I ended up using a docker container though for JDK13, and to modify `start.sh` for output to stdio rather than nohup (to help debug Java errors).
