### ISSUE TITLE
Right mouse button

### ISSUE THREAD

**Issue by sirolf2009** [JPro-one/JPro-tickets#8]
I have an application that contains chart that where you can pan around with the right mouse button. If I try it with JPro I'll keep getting the context menu.

**Comment by FlorianKirmaier** [comment]
Hi @sirolf2009,

there is a field for the jpro-tag, which can be set to enable the javafx-contextmenu:
<jpro-app ... fxContextMenu="true"/>
It's also mentioned in our documentation: [https://www.jpro.one/?page=docs/current/2.3/EMBEDDING_JPRO](https://www.jpro.one/?page=docs/current/2.3/EMBEDDING_JPRO)

**Comment by sirolf2009** [comment]
Works like a charm, cheers!
