### ISSUE TITLE
BellSoftJDK - HelloJPro Sample app: NoClassDefFoundError DefaultCanvasAccessor

### ISSUE THREAD

**Issue by nohochmak** [JPro-one/JPro-tickets#80]
**Environment:**
[info] c.j.i.s.Initializer$ - OS: Mac OS X
[info] c.j.i.s.Initializer$ - JPro: 2020.1.2-SNAPSHOT
[info] c.j.i.s.Initializer$ - Java version: 11.0.9
[info] c.j.i.s.Initializer$ - JVM: 11.0.9 BellSoft
[info] c.j.i.s.Initializer$ - JavaFX version: 11.0.9+b01

**When running with Gradle or Maven -same errors: (Also tried with JavaFX 13,15 **

[info] c.j.i.s.MonocleInitializer$ - screen: null
[error] c.j.i.s.Initializer$ - error while applying configuration Init Canvas Accessor:
**java.lang.NoClassDefFoundError: javafx/scene/canvas/Canvas$DefaultCanvasAccessor**
...

[info] c.j.i.s.ViewSerializerActor - appdef: AppByMain(hellojpro,com.jpro.hellojpro.HelloJProFXML,None,NamedClassLoader(system),false) clientinfo: ClientInfo(http://localhost:8080/,http://localhost:8080/app/hellojpro,1748.0,903.0,false,en-US,List(en-US, en),,Map(),Map(DNT -> List(1), Host -> List(localhost:8080), Accept -> List(*/*), Origin -> List(http://localhost:8080), Pragma -> List(no-cache), Upgrade -> List(websocket), Connection -> List(keep-alive, Upgrade), User-Agent -> List(Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0), Cache-Control -> List(no-cache), Remote-Address -> List(127.0.0.1:50554), Timeout-Access -> List(<function1>), Accept-Encoding -> List(gzip, deflate), Accept-Language -> List(en-US,en;q=0.5), Raw-Request-URI -> List(/app/0!hellojpro), Tls-Session-Info -> List(Session(1609985471141|SSL_NULL_WITH_NULL_NULL)), Sec-WebSocket-Key -> List(tpjY/cpfJdGAEV1JA6iZGA==), UpgradeToWebSocket -> List(), Sec-WebSocket-Version -> List(13), Sec-WebSocket-Extensions -> List(permessage-deflate)))out: Actor[akka://application/system/Materializers/StreamSupervisor-0/$$k-actorRefSource#2017267247]
**java.lang.NoSuchMethodError: 'void javafx.scene.Scene.addPreRenderPulseListener(java.lang.Runnable)'**

**Comment by FlorianKirmaier** [comment]
I think bellsoft adds it's own JavaFX-Version, which collides with our JavaFX-Fork.
Since JavaFX11, JavaFX is usually no longer part of most JDKs.
BellSoft also seems to provide a JDK without their JavaFX Fork - which should solve the problem.

They are probably adding JavaFX to make the transition from Java 8 to 11 easier, but it's usually better to have JavaFX independent of the JDK for various reasons.

**Comment by nohochmak** [comment]
Yes you are correct - I ran this with 13.0.2.j9-adpt (via sdkman) and it works great.  Thanks for your quick response.

**Comment by FlorianKirmaier** [comment]
Great!
