### ISSUE TITLE
jproStart run error[Gradle]

### ISSUE THREAD

**Issue by SchweinchenFuntik** [JPro-one/JPro-tickets#81]
Gradle version - 6.6.1

**build.gradle.kts**
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.4.21"
    application
    id("com.sandec.jpro") version "2020.1.2"
    id("org.openjfx.javafxplugin") version "0.0.9"
}

group = "group"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test-junit5"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.0")
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "11"
}

tasks.withType<JavaCompile> {
    sourceCompatibility = "11"
    targetCompatibility = "11"
}

application {
    mainClassName = "test.TestFxApp"
}

javafx {
    version = "15"
    modules = listOf("javafx.base", "javafx.graphics", "javafx.controls", "javafx.fxml", "javafx.media", "javafx.web")
}

jpro {
    @Suppress("UNCHECKED_CAST")
    (jvmArgs as? MutableList<Any?>)?.let { it.add("-Xmx256m") }
    port = 8088
    releasePlatforms = arrayOf("linux")
}
```
**settings.gradle.kts**
```kotlin
rootProject.name = "TestFxWebApp"

pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.sandec.jpro") {
                useModule("com.sandec.jpro:jpro-plugin-gradle:${requested.version}")
            }
        }
    }

    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven("https://sandec.bintray.com/repo")
    }
}

```

**console:** `./gradlew jproRun`
```
> Task :jproStartAsync FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jproStartAsync'.
> This application is already running (Or delete /home/username/.gradle/daemon/6.6.1/RUNNING_PID file).

```

PS: The file is not there. I run only one gradle (checked the absence of processes)

**Comment by SchweinchenFuntik** [comment]
Found this file in the project folder

**Comment by FlorianKirmaier** [comment]
It looks like it's starting the JVM from the wrong directory for some reason.
Or the RUNNING_PID is created/checked from the wrong directory.
That's a bug which we will fix very soon. We will provide a SNAPSHOT build of the fix when it is ready.

Does JPro start properly for you? I can reproduce the error, but the application starts properly in my environment.

**Comment by SchweinchenFuntik** [comment]
application starts correctly, everything is fine. The error was due to the fact that the previous launch of gradle did not complete correctly and the PID file was not deleted, I deleted it and everything is ok.

But I would like the plugin to correctly indicate the directory to this pid file.

In principle, the problem is solved, I think you can close this question if you do not need it as a marker

**Comment by FlorianKirmaier** [comment]
We fixed the issue with the wrong directory. It should now point to the correct PID file. 
The plugin also stops the process by default, which should now work properly.
You can test it, by using the JProVersion `2020.1.3-SNAPSHOT`
