### ISSUE TITLE
java.lang.NoClassDefFoundError: javafx/scene/canvas/Canvas$DefaultCanvasAccessor

### ISSUE THREAD

**Issue by Hugolarson** [JPro-one/JPro-tickets#84]
Getting this error with my own project and also JPro-Samples
Find attached log files

Windows 10
JPRO_VERSION=2020.1.4
JDK-15

UPDATE:
Same problem on Ubuntu 20

FEATURE
It would be good if one could set java path in Gradle, also so start.sh uses java on that path.

[jpro.error.log](https://github.com/JPro-one/JPro-tickets/files/6007526/jpro.error.log)

**Comment by FlorianKirmaier** [comment]
Which JDK are you using exactly?
Some JDK's have an own fork of JavaFX which is added to the classpath by the JVM - just like it was done with Java8.
These JDK's can cause issues with our forked version of JavaFX:

**Comment by Hugolarson** [comment]
Azul java 15 packed with JavaFX 
So now JPro download FX on its own?
What about the JavaFX .DLL and .SO files (jmods)?

UPDATE:
UBUNTU 20. Installed default jre with "apt-get install default-jdk" 
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

EXCEPTION:
java.lang.UnsatisfiedLinkError: no javafx_font_pango in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni,/lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]

**Comment by FlorianKirmaier** [comment]
I think Azul also provides a version of the JDK without JavaFX.
Since Java(FX)11, JavaFX is usually downloaded from maven. (Except some rare JVM's which do it like Java8)
The native libraries are somehow loaded in the library. I don't know the details about it, but it works, and you don't have to worry about it.

For ubuntu, you will have to install the following packages:
```sudo apt-get install xorg gtk2-engines libasound2 libgtk2.0-0```
Taken from the documentation: https://www.jpro.one/?page=docs/current/2.7/PREPARING_LINUX_FOR_JPRO

**Comment by Hugolarson** [comment]
Tried JPRO with several JRE build vendors with JavaFX and all of them caused this problem.
Solution is run JPRO with JRE without JavaFX.
I think this is a problem and should be fixed.

**Comment by FlorianKirmaier** [comment]
Yes, thank you for the feedback.
We will add more detailed error-messages, when using a JDK with JavaFX.

A JRE with JavaFX just isn't the way to go nowadays. This is only done by the JRE vendors to help people to skip a proper migration. For JavaFX it's also way better to be independent of the JRE.

**Comment by FlorianKirmaier** [comment]
The next version will contain an ErrorMessage, so the user knows the Bundled JavaFX is the Problem. 
I'm closing the ticket, therefore.
