### ISSUE TITLE
JPro inside docker, error on container restart

### ISSUE THREAD

**Issue by garzy** [JPro-one/JPro-tickets#92]
Hi, I've followed the docker instructions to launch my JavaFX on my ubuntu server (https://cv.tangorabox.com).

It works well but when I restart the container I'm having this error

> This application is already running (or delete /ResumeFX-jpro/RUNNING_PID file). JPro will be started.

And the container enters in an infinite restart tryout and it's impossible to access inside the docker console through its terminal to delete the PID file (because is restarting forever).

How can I fix this?

_For now, the only solution that I've found has been deleting the container and creating another with the same image._

Some log info about JPro and Java Versions:
```
[info] a.e.s.Slf4jLogger - Slf4jLogger started

[info] play.api.Play - Application started (Prod) (no global state)

[info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:8080

[info] c.jpro.activity - Starting the server

[info] c.j.i.s.Initializer$ -  *** Starting JPro: https://www.jpro.one/ ***

[info] c.j.i.s.Initializer$ - OS: Linux

[info] c.j.i.s.Initializer$ - **JPro: 2021.1.0-PREVIEW2**

[info] c.j.i.s.Initializer$ - **Java version: 15.0.2**

[info] c.j.i.s.Initializer$ - **JVM: 15.0.2 AdoptOpenJDK**

[info] c.j.i.s.Initializer$ - redirected OUT / ERR

[info] c.j.i.s.Initializer$ - installed SLF4JBridge

[info] c.j.i.s.MonocleInitializer$ - screen: null

[warn] javafx - Unsupported JavaFX configuration: classes were loaded from 'unnamed module @53b64742'

[info] c.j.i.s.Initializer$ - finished init!

[info] c.j.i.s.Initializer$ - **JavaFX version: 16-jpro+0-2021-04-11-181717**

[info] c.j.i.c.m.ChartJSONImExporter - Nothing to import

[info] c.j.i.c.m.DynamicDataModel - Started Monitoring chart data...

[info] c.jpro - application requested: 0!website

[info] c.jpro - Creating Application: 0!website

[info] c.jpro - remoteAddress 172.28.0.1

[info] c.jpro - host          cv.tangorabox.com

[info] c.jpro - uri           /app/0!website
```

**Comment by FlorianKirmaier** [comment]
Forgot to mention it. Somehow forgot this ticket. We are gonna look into it.

**Comment by FlorianKirmaier** [comment]
Don't know whether it's still relevant. The docker file in the JProRelease uses the restart-script, which deletes the RUNNING.PID file, which should end to a proper start, when the container is restarted.

**Comment by garzy** [comment]
OK, thank you very much, I was running the `start.sh` command instead of `restart.sh`

I changed it, and its works like a charm! 

Thank you! ;)
