### ISSUE TITLE
Path ignores stroke line cap

### ISSUE THREAD

**Issue by mipastgt** [JPro-one/JPro-tickets#98]
I am trying to render a track on a map for which native JavaFX gives me the following correct result.

<img width="410" alt="jfx-correct" src="https://user-images.githubusercontent.com/16735714/115891721-afe38b80-a456-11eb-8075-381273fc1545.png">

The track consists of a simple Polyline (red) and a Path (blue). For the Path each point of the track is drawn as a zero length line segment via moveTo/lineTo pairs with the same coordinate. The stroke width is set to 10 and the caps are set to round. This results in the above bullet line on top of the Polyline.

When I render this with JPro I only see the red Polyline and no bullets.

<img width="352" alt="jpro-wrong1" src="https://user-images.githubusercontent.com/16735714/115893823-ea4e2800-a458-11eb-97c7-010ea933fd8f.png">

If I artificially add a little delta between the line ends, I see the following:

<img width="450" alt="jpro-wrong2" src="https://user-images.githubusercontent.com/16735714/115892989-ff768700-a457-11eb-87be-29a8e2df20b8.png">

By playing with different values I can see that the lines are drawn with the correct width but the line cap setting is just completely ignored and defaults to butt. That's the reason why a zero length line is not visible at all.

This test was done locally with Chrome and
```
[info] c.j.i.s.Initializer$ - OS: Mac OS X
[info] c.j.i.s.Initializer$ - JPro: 2021.1.0-PREVIEW2
[info] c.j.i.s.Initializer$ - Java version: 15.0.2
[info] c.j.i.s.Initializer$ - JVM: 15.0.2 Oracle Corporation
```

**Comment by FlorianKirmaier** [comment]
Looks like this just was never implemented. We've got locally a fixed version. Later today we will provide a version with both this fix and the new device-pixel-ratio API.

**Comment by FlorianKirmaier** [comment]
Try out the version `2021.1.0-PREVIEW2`.
With this version, the strokeLineCap should be correct, also for lines with 0 length.

**Comment by mipastgt** [comment]
But I have used that version already in my original report. See log output.

**Comment by FlorianKirmaier** [comment]
Somehow thought this version was only used internally and I've reused the version name. 
I've just made a new version `2021.1.0-PREVIEW3`.

**Comment by mipastgt** [comment]
Just verified that the output looks identical now for JPro and native JavaFX. Thanks a lot.

**Comment by mipastgt** [comment]
I think this is fixed and can be closed now.
